= Pkl Project Commons

This repository houses libraries that are implementation details for the Pkl project.

These libraries are not meant for general use.

== Publishing packages

To publish a package, run `./scripts/publish_package.sh` with the name of the package.

For example:

[source,bash]
----
./scripts/publish_package.sh pkl.impl.ghactions
----

== Updating `pkl.impl.ghactions`

There is a script in `./scripts/update_downstream_ci.sh` that auto-bumps the `pkl.impl.ghactions` package in every downstream repository.

This script should be run whenever a new package is published.

This tool assumes:

1. You have `pkl`, `jq`, and `gh` installed.
2. You are logged into `gh`.
3. You have every downstream repo forked onto your personal GitHub account.

== Internal IntelliJ Plugin

There is an IntelliJ plugin to help with working on Pkl-related repos.

This plugin provides a split pane window when viewing snippet tests such as LanguageSnippetTests and FormatterSnippetTests.

To install:

1. Run `./gradlew pkl-internal-intellij-plugin:buildPlugin`.
2. Within IntelliJ, run the action "Install Plugin From Disk...".
3. Select the zip file within `pkl-internal-intellij-plugin/build/distributions`.
